complete the "user story set up" function
buse2017fall/SoftwareEngineering pull request #16
Opened 2017-10-18 18:13 UTC by tl47704n

2017-10-18 22:14 UTC, buse2017fall requested changes

2017-10-18 22:14 UTC, buse2017fall commented on project/themes/default/index.php
> +<!--<span id="taskview" class="mtt-menu-button"><span class="btnstr"><?php _e('tasks');?></span> (<span id="total">0</span>) <span class="arrdown"></span></span> -->
1.did you test it on your local machine ? 
2.did you sync up with designer leader about the front-end design ?

2017-10-19 14:30 UTC, tl47704n commented
Yes I tested and weicheng and I worked together on that

发自我的 iPhone

在 2017年10月18日，下午6:14，buse2017fall <notifications@github.com<mailto:notifications@github.com>> 写道：


@buse2017fall requested changes on this pull request.

________________________________

In project/themes/default/index.php<https://github.com/buse2017fall/SoftwareEngineering/pull/16#discussion_r145557581>:

> @@ -155,7 +155,7 @@

 <h3>

-<span id="taskview" class="mtt-menu-button"><span class="btnstr"><?php _e('tasks');?></span> (<span id="total">0</span>) <span class="arrdown"></span></span>
+<!--<span id="taskview" class="mtt-menu-button"><span class="btnstr"><?php _e('tasks');?></span> (<span id="total">0</span>) <span class="arrdown"></span></span> -->


1.did you test it on your local machine ?
2.did you sync up with designer leader about the front-end design ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/buse2017fall/SoftwareEngineering/pull/16#pullrequestreview-70375532>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AWGjOGOLQaAA-pOtPJbG-ipti0OVLwTuks5stnhEgaJpZM4P-Is3>.

2017-10-19 14:32 UTC, buse2017fall approved these changes
Ship it

2017-10-19 14:33 UTC, merged